#!/usr/bin/env bash

# Required packages
echo "Installing sudo and git"
pacman -S --noconfirm sudo

# Configuring user
source ~/arch_inst/00-user
source ~/arch_inst/00-platform

read -r -p "Enter password for user $USER: " PASSWD
echo "Adding $USER"
useradd -m "$USER" -p $PASSWD
echo "Adding groups to $USER"
usermod -aG wheel,audio,video,optical,storage "$USER"
echo "Changing sudoers"
sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers
sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers
echo "Changing user to $USER"
su - "$USER"
git clone https://github.com/mediocreeee/arch_inst && cd arch_inst
