#!/usr/bin/env bash

# Installing base packages
echo "Installing loads of packages"
sudo pacman -S --noconfirm base-devel xorg awesome neovim compton flameshot firefox ranger newsboat \
	discord telegram-desktop termite transmission-gtk alsa alsa-utils pulseaudio feh mpv \
	ripgrep neofetch youtube-dl chafa w3m fzf the_silver_searcher lxappearance bat ncdu \
	mpd mpc ncmpcpp networkmanager network-manager-applet blueberry unclutter pavucontrol wget \
	zathura zathura-djvu zathura-pdf-mupdf zathura-cb libreoffice-still thunar tumbler arandr \
	zsh openssh lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings ueberzug fd \
	grub-customizer cronie devmon texlive-most texlive-lang jq tldr shellcheck shfmt bc gksu \
	gdb valgrind alacritty rsync

echo "Enabling lightdm"
sudo systemctl enable lightdm
echo "Enabling sshd"
sudo systemctl enable sshd
echo "Enabling NetworkManager"
sudo systemctl enable NetworkManager
echo "Enabling cronie"
sudo systemctl enable cronie
