#!/usr/bin/env bash

# Installing base packages
echo "Installing loads of packages"
sudo pacman -S --noconfirm base-devel xorg awesome neovim compton flameshot firefox ranger newsboat \
	discord telegram-desktop termite transmission-gtk alsa alsa-utils pulseaudio feh mpv \
	ripgrep neofetch youtube-dl chafa w3m fzf the_silver_searcher lxappearance bat ncdu ttf-joypixels \
	mpd mpc ncmpcpp networkmanager network-manager-applet blueberry unclutter pavucontrol \
	zathura zathura-djvu zathura-pdf-mupdf zathura-cb libreoffice-still thunar tumbler arandr \
	zsh openssh lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings ttf-font-awesome \
	grub-customizer cronie devmon

echo "Enabling lightdm"
sudo systemctl enable lightdm
echo "Enabling sshd"
sudo systemctl enable sshd
echo "Enabling NetworkManager"
sudo systemctl enable NetworkManager
echo "Enabling cronie"
sudo systemctl enable cronie
