#!/usr/bin/env bash

# Setup awesomewm
echo "Cloning modalbind from github"
cd ~/.config/awesome && git clone https://github.com/crater2150/awesome-modalbind.git && mv awesome-modalbind modalbind && cd
