#!/usr/bin/env bash

# Setup nerd-fonts
echo "Installing nerd-fonts"
sudo pacman -S --noconfirm ttf-joypixels ttf-font-awesome
cd ~
cd ~/trsh && git clone https://github.com/ryanoasis/nerd-fonts && cd nerd-fonts && ./install.sh
