#!/usr/bin/env bash

# Install oh-my-zsh
echo "Removing existing oh-my-zsh"
rm -rf ~/.oh-my-zsh
echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
