#!/usr/bin/env bash

# Setup yay
cd ~
echo "Setuping yay"
cd ~/progs && git clone https://aur.archlinux.org/yay.git && cd yay && yes | makepkg -si
echo "Updating system with yay"
yay --answerdiff=None --noconfirm -Syyuu
