#!/usr/bin/env bash

# Setup setxkbmap xinput and xorg startup
echo "Setting setxkbmap"
sudo cat <<EOF | sudo tee /etc/X11/xorg.conf.d/00-keyboard.conf
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ru,ua"
        Option "XkbModel" "pc104"
        Option "XkbVariant" "qwerty"
        Option "XkbOptions" "grp:caps_toggle"
EndSection
EOF
