#!/usr/bin/env bash

source ~/arch_inst/00-platform

echo "Setting xinput..."
case $PLATFORM in
"PC")
	sudo cat <<EOF | sudo tee /etc/X11/xorg.conf.d/99-libinput.conf
Section "InputClass"
  Identifier "My config"
  MatchDriver "libinput"
  MatchProduct "SINOWEALTH Wired Gaming Mouse"
  Option "AccelSpeed" "-0.8"
EndSection
EOF
	;;

"LAPTOP")
	sudo cat <<EOF | sudo tee /etc/X11/xorg.conf.d/99-libinput.conf
Section "InputClass"
  Identifier "My trackpoint config"
  MatchDriver "libinput"
  MatchProduct "TPPS/2 IBM TrackPoint"
  Option "AccelSpeed" "-0.8"
EndSection
EOF
	;;
esac
