#!/usr/bin/env bash

# GTK Themes
git clone https://github.com/4rtzel/Gruvbox-Dark-Yellow ~/.themes/Gruvbox-Dark-Yellow
sudo pacman -S --noconfirm arc-gtk-theme
# Breeze cursor
yay -S --noconfirm --answerdiff=None breeze-snow-cursor-theme
