#!/usr/bin/env bash

USER=$(whoami)

# Betterlockscreen
echo "Installing betterlockscreen"
yay -S --noconfirm --answerdiff=None betterlockscreen
cat <<EOF | sudo tee /etc/systemd/system/betterlockscreen@.service
[Unit]
Description = Lock screen when going to sleep/suspend
Before=sleep.target
Before=suspend.target

[Service]
User=%I
Type=simple
Environment=DISPLAY=:0
ExecStart=/usr/bin/betterlockscreen --lock
TimeoutSec=infinity
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
WantedBy=suspend.target
EOF

echo "Enabling betterlockscreen"
sudo systemctl enable betterlockscreen@$USER
