#!/usr/bin/env bash

source ./00-platform

# shell-color-scripts
if [ "$PLATFORM" = "PC" ]; then
	cd trsh && git clone https://gitlab.com/dwt1/shell-color-scripts.git
	cd shell-color-scripts
	sudo rm -rf /opt/shell-color-scripts || return 1
	sudo mkdir -p /opt/shell-color-scripts/colorscripts || return 1
	sudo cp -rf colorscripts/* /opt/shell-color-scripts/colorscripts
	sudo cp colorscript.sh /opt/shell-color-scripts/
	cd ~
fi
