#!/usr/bin/env bash

USER="mediocreeee"

mkdir ~/code
cd ~/code

REPOS=$(curl https://api.github.com/users/"$USER"/repos |
	jq 'map(.full_name)' | grep -v '\[\|\]' | tr -d \" | tr -d ,)

for repo in $REPOS; do
	git clone https://github.com/"$repo"
done
