#!/usr/bin/env bash

GIT_USER="mediocreeee"
cd ~
mkdir ~/code
cd ~/code

REPOS=$(curl https://api.github.com/users/"$GIT_USER"/repos |
	jq 'map(.full_name)' | grep -v '\[\|\]' | tr -d \" | tr -d ,)

for repo in $REPOS; do
	git clone https://github.com/"$repo"
done
