#!/usr/bin/env bash

read -r -p "Choose platform:
1. PC
2. LAPTOP

" PLATFORM

case $PLATFORM in
1)
	PLATFORM="PC"
	CLONE_DOTFILES="git clone https://github.com/mediocreeee/dotfiles"
	;;
2)
	PLATFORM="LAPTOP"
	CLONE_DOTFILES="git clone https://github.com/mediocreeee/dotfiles --branch laptop --single-branch"
	;;
*)
	echo "Please select platform correctly"
	exit 1
	;;
esac

# Network config
echo "Setup dhcpcd"
systemctl enable dhcpcd && systemctl start dhcpcd
echo "Updating system with pacman"
pacman -Syyuu

# Required packages
echo "Installing sudo and git"
pacman -S --noconfirm sudo

# Configuring user
read -r -p "Enter username: " USER
read -r -p "Enter password for user $USER: " PASSWD
echo "Adding $USER"
useradd -m "$USER" -p "$PASSWD"
echo "Adding groups to $USER"
usermod -aG wheel,audio,video,optical,storage "$USER"
echo "Changing sudoers"
sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers
sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers
echo "Changing user to $USER"
# Cloning arch_inst to $USER
echo "Cloning arch_inst to $USER"
git clone https://github.com/mediocreeee/arch_inst /home/$USER/arch_inst && cd arch_inst
# Changing user
su - "$USER"
