#!/usr/bin/env bash

# 01
# Network config
echo "Setup dhcpcd"
systemctl enable dhcpcd && systemctl start dhcpcd
echo "Updating system with pacman"
pacman -Syyuu

# 02
# Required packages
echo "Installing sudo and git"
pacman -S --noconfirm sudo

# Configuring user
read -r -p "Enter username: " USER

echo "Adding $USER"
useradd -m $USER
passwd $USER
echo "Adding groups to $USER"
usermod -aG wheel,audio,video,optical,storage "$USER"
echo "Changing sudoers"
sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers
sed --in-place 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers
echo "Cloning installation script to $USER folder"
git clone https://github.com/mediocreeee/arch_inst /home/$USER/arch_inst
echo "Changing user to $USER"
su - "$USER"
